# Generated by Django 5.2.4 on 2025-07-28 05:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.CharField(blank=True, max_length=500, null=True)),
                ('matching_answer', models.JSONField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(help_text="For Fill in the Blank, use '___'. For Matching, describe the task, e.g., 'Match the number to the image.'", max_length=500, verbose_name='Question Text')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice (Text)'), ('MCQI', 'Multiple Choice (Image)'), ('TF', 'True/False'), ('SA', 'Short Answer'), ('FITB', 'Fill in the Blank'), ('MATCH', 'Matching (Text)'), ('MATI', 'Matching (Image/Mixed)')], max_length=5, verbose_name='Question Type')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Order')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academics.unit')),
            ],
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.CharField(blank=True, help_text='Use for text prompts.', max_length=255, null=True, verbose_name='Prompt Text')),
                ('match_text', models.CharField(blank=True, help_text='Use for text matches.', max_length=255, null=True, verbose_name='Correct Match Text')),
                ('prompt_image', models.ImageField(blank=True, help_text='Use for image prompts.', null=True, upload_to='matching_images/', verbose_name='Prompt Image')),
                ('match_image', models.ImageField(blank=True, help_text='Use for image matches.', null=True, upload_to='matching_images/', verbose_name='Correct Match Image')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='quizzes.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(blank=True, help_text='Use for text-based answers (MCQ, TF, SA, FITB).', max_length=500, null=True, verbose_name='Answer Text')),
                ('answer_image', models.ImageField(blank=True, help_text='Use for image-based choice questions (MCQI).', null=True, upload_to='answer_images/', verbose_name='Answer Image')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is Correct')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.question')),
            ],
        ),
    ]
