# Generated by Django 5.2.4 on 2025-07-29 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_unit_unique_together_unit_duration_minutes_and_more'),
        ('quizzes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='time_taken_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Time Taken (seconds)'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='academics.unit'),
        ),
    ]
