# Generated by Django 5.2.4 on 2025-07-28 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Grade 1, Grade 2', max_length=100, unique=True, verbose_name='Grade Name')),
                ('description', models.TextField(blank=True, help_text='A brief description of the grade level.', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="The title of the unit, e.g., 'Addition Basics'", max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='What this unit covers.', null=True, verbose_name='Description')),
                ('unit_number', models.PositiveIntegerField(default=1, help_text='The order of the unit within the grade.', verbose_name='Unit Number')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='academics.grade', verbose_name='Grade')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['grade', 'unit_number'],
                'unique_together': {('grade', 'unit_number')},
            },
        ),
    ]
