# Generated by Django 5.2.4 on 2025-07-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_unit_unique_together_unit_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Check this box to make the unit visible to students.'),
        ),
    ]
